version: "3"

vars:
  GO: go
  MISSPELL_FLAGS: -error -locale US
  STATICCHECK_FLAGS: -checks all,-SA1029,-SA9003,-ST1000,-ST1003,-ST1016,-ST1020,-ST1021,-ST1022,-ST1023

tasks:
  default:
    cmds:
      - task: fast

  fast:
    desc: run a fast lint/test suite
    requires:
      vars: [GO]
    cmds:
      - task: goimports
      - task: staticcheck
      - task: misspell
      - task: unparam
      - task: govet
      - task: gotest

  full:
    desc: run a full lint/test suite
    cmds:
      - task: default
      - task: govulncheck

  githook:
    desc: same as "fast," but changes are automatically applied if possible
    requires:
      vars: [GO]
    cmds:
      - task: goimports
        vars: {EXTRA_ARGS: -fix}
      - task: staticcheck
      - task: misspell
        vars: {EXTRA_ARGS: -w}
      - task: unparam
      - task: govet
      - task: gotest

  goimports:
    desc: (lint, fast) run goimports
    preconditions:
      - sh: command -v goimports
        msg: run '{{.GO}} install golang.org/x/tools/cmd/goimports@latest' and try again
    shopt: [globstar]
    requires:
      vars: [GO]
    cmds:
      - "{{.GO}} run ./devtools/checkimports {{.EXTRA_ARGS}} *.go **/*.go"

  gotest:
    desc: (lint, fast) run go test
    requires:
      vars: [GO]
    cmds:
      - "{{.GO}} test ./..."

  govet:
    desc: (lint, fast) run go vet
    requires:
      vars: [GO]
    cmds:
      - "{{.GO}} vet ./..."

  staticcheck:
    desc: (lint, fast) run staticcheck
    preconditions:
      - sh: command -v staticcheck
        msg: run '{{.GO}} install honnef.co/go/tools/cmd/staticcheck@latest' and try again
    cmds:
      - "staticcheck {{.STATICCHECK_FLAGS}} ./..."

  misspell:
    desc: (lint, fast) run misspell
    preconditions:
      - sh: command -v misspell
        msg: run '{{.GO}} install github.com/client9/misspell/cmd/misspell@latest' and try again
    shopt: [globstar]
    cmds:
      - misspell {{.EXTRA_ARGS}} {{.MISSPELL_FLAGS}} -source go **/*.go
      - misspell {{.EXTRA_ARGS}} {{.MISSPELL_FLAGS}} CONTRIBUTING LICENSE README

  unparam:
    desc: (lint, fast) run unparam
    preconditions:
      - sh: command -v unparam
        msg: run '{{.GO}} install mvdan.cc/unparam@latest' and try again
    cmds:
      - unparam ./...

  govulncheck:
    desc: (lint) run govulncheck
    preconditions:
      - sh: command -v govulncheck
        msg: run '{{.GO}} install golang.org/x/vuln/cmd/govulncheck@latest' and try again
    cmds:
      - govulncheck ./...
